version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: employee_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - employee_network

  api:
    build: .
    container_name: employee_api
    restart: always
    ports:
      - '3000:3000'
    environment:
      PORT: '3000'
      MONGO_URI: 'mongodb://root:password@mongodb:27017/employee_management?authSource=admin'
    depends_on:
      - mongodb
    networks:
      - employee_network

volumes:
  mongodb_data:

networks:
  employee_network:
    driver: bridge
